/**
 * Where a company's shares trade, read from research/listings.json.
 *
 * That file is generated by `scripts/research/listings.ts` from the SEC and
 * OpenFIGI and committed like the rest of the corpus, so a ticker on a page
 * is a row someone can diff, with the source it came from beside it.
 */
import listingsFile from '../research/listings.json';
import { MARKET_PARTICIPANTS } from './participants';

export interface SecurityRef {
  ticker: string;
  /** SEC exchange name ("Nasdaq", "NYSE", "OTC") or Bloomberg composite code ("JP", "KS"). */
  exchange: string;
  /** The security's name at the source, which is how a match can be checked. */
  name: string;
  figi?: string;
  /** SEC registrant id; present when EDGAR has filings for it. */
  cik?: number;
  source: string;
}

export type Listing =
  | {
      status: 'listed' | 'parent';
      /** Set when the listing is a parent company's. */
      parent?: string;
      note?: string;
      primary: SecurityRef | null;
      us: SecurityRef | null;
      checkedOn: string;
    }
  | { status: 'private'; note: string; checkedOn: string }
  | { status: 'none-found'; query: string; checkedOn: string };

export interface ListingsFile {
  version: 1;
  checkedOn: string;
  listings: Record<string, Listing>;
}

/**
 * Bloomberg composite exchange codes by country (ISO 3166-1 alpha-2). A
 * composite is the country-level line a terminal quotes — "8035 JP", not one
 * venue's line of it.
 */
export const HOME_COMPOSITE: Record<string, string> = {
  US: 'US',
  JP: 'JP',
  KR: 'KS',
  TW: 'TT',
  NL: 'NA',
  DE: 'GR',
  FR: 'FP',
  GB: 'LN',
  CH: 'SW',
  IT: 'IM',
  BE: 'BB',
  CN: 'CH',
  HK: 'HK',
  AU: 'AU',
  CA: 'CN',
  ZA: 'SJ',
  NO: 'NO',
  DK: 'DC',
  SE: 'SS',
  AT: 'AV',
  PL: 'PW',
  SG: 'SP',
  MY: 'MK',
  ID: 'IJ',
  PE: 'PE',
  RU: 'RU',
  FI: 'FH',
  IN: 'IN',
  ES: 'SM',
  IE: 'ID',
  IL: 'IT',
  BR: 'BZ',
  CL: 'CI',
  QA: 'QD',
  SA: 'AB',
};

export const LISTINGS = listingsFile as ListingsFile;

export function listingFor(slug: string): Listing | undefined {
  return LISTINGS.listings[slug];
}

const SLUG_BY_NAME = new Map(MARKET_PARTICIPANTS.map((p) => [p.name, p.slug]));

/** By the directory name a producer row uses. Null when the holder has no directory page. */
export function listingForName(name: string): Listing | null {
  const slug = SLUG_BY_NAME.get(name);
  return slug ? (LISTINGS.listings[slug] ?? null) : null;
}

/** "8035 JP" / "ASML US" — the form a terminal takes. */
export function terminalTicker(ref: SecurityRef): string {
  const exchange = ref.figi ? ref.exchange : 'US';
  return `${ref.ticker} ${exchange}`;
}

/** Every EDGAR registrant among the directory's companies, once each. */
export function edgarRegistrants(): { cik: number; slugs: string[]; name: string }[] {
  const byCik = new Map<number, { cik: number; slugs: string[]; name: string }>();
  for (const [slug, listing] of Object.entries(LISTINGS.listings)) {
    if (listing.status !== 'listed' && listing.status !== 'parent') continue;
    const cik = listing.us?.cik;
    if (!cik) continue;
    const seen = byCik.get(cik);
    if (seen) seen.slugs.push(slug);
    else byCik.set(cik, { cik, slugs: [slug], name: listing.us!.name });
  }
  return [...byCik.values()];
}
