/**
 * Every landmass on the map. Generated from world-paths + UN-ish regions.
 * Re-run: python3 scripts/research/generate-countries.py
 * Resources still live in substrata-resources.ts and are joined at read time.
 */
export type PathRole =
  | 'extract'
  | 'refine'
  | 'manufacture'
  | 'energy'
  | 'capital'
  | 'permission'
  | 'logistics'
  | 'research'
  | 'gap';

export type CountryIndex = {
  iso2: string;
  name: string;
  region: string;
  roles: readonly PathRole[];
};

export const COUNTRIES: readonly CountryIndex[] = [
  { iso2: 'fj', name: 'Fiji', region: 'Oceania', roles: ['extract'] },
  { iso2: 'tz', name: 'Tanzania', region: 'East Africa', roles: ['extract'] },
  { iso2: 'eh', name: 'W. Sahara', region: 'North Africa', roles: ['gap'] },
  { iso2: 'ca', name: 'Canada', region: 'North America', roles: ['gap'] },
  {
    iso2: 'us',
    name: 'United States of America',
    region: 'North America',
    roles: ['extract', 'manufacture', 'energy', 'permission', 'capital', 'research'],
  },
  { iso2: 'kz', name: 'Kazakhstan', region: 'Central Asia', roles: ['gap'] },
  { iso2: 'uz', name: 'Uzbekistan', region: 'Central Asia', roles: ['gap'] },
  { iso2: 'pg', name: 'Papua New Guinea', region: 'Oceania', roles: ['extract'] },
  { iso2: 'id', name: 'Indonesia', region: 'Southeast Asia', roles: ['gap'] },
  { iso2: 'ar', name: 'Argentina', region: 'South America', roles: ['gap'] },
  { iso2: 'cl', name: 'Chile', region: 'South America', roles: ['gap'] },
  { iso2: 'cd', name: 'Dem. Rep. Congo', region: 'Central Africa', roles: ['gap'] },
  { iso2: 'so', name: 'Somalia', region: 'East Africa', roles: ['gap'] },
  { iso2: 'ke', name: 'Kenya', region: 'East Africa', roles: ['extract'] },
  { iso2: 'sd', name: 'Sudan', region: 'North Africa', roles: ['extract'] },
  { iso2: 'td', name: 'Chad', region: 'Central Africa', roles: ['extract'] },
  { iso2: 'ht', name: 'Haiti', region: 'Caribbean', roles: ['extract'] },
  { iso2: 'do', name: 'Dominican Rep.', region: 'Caribbean', roles: ['extract'] },
  { iso2: 'ru', name: 'Russia', region: 'Eastern Europe', roles: ['gap'] },
  { iso2: 'bs', name: 'Bahamas', region: 'Caribbean', roles: ['gap'] },
  { iso2: 'fk', name: 'Falkland Is.', region: 'South America', roles: ['gap'] },
  { iso2: 'no', name: 'Norway', region: 'Northern Europe', roles: ['gap'] },
  { iso2: 'gl', name: 'Greenland', region: 'North America', roles: ['extract'] },
  { iso2: 'tf', name: 'Fr. S. Antarctic Lands', region: 'Antarctica', roles: ['gap'] },
  { iso2: 'tl', name: 'Timor-Leste', region: 'Southeast Asia', roles: ['extract'] },
  { iso2: 'za', name: 'South Africa', region: 'Southern Africa', roles: ['gap'] },
  { iso2: 'ls', name: 'Lesotho', region: 'Southern Africa', roles: ['gap'] },
  { iso2: 'mx', name: 'Mexico', region: 'North America', roles: ['gap'] },
  { iso2: 'uy', name: 'Uruguay', region: 'South America', roles: ['extract'] },
  { iso2: 'br', name: 'Brazil', region: 'South America', roles: ['gap'] },
  { iso2: 'bo', name: 'Bolivia', region: 'South America', roles: ['gap'] },
  { iso2: 'pe', name: 'Peru', region: 'South America', roles: ['gap'] },
  { iso2: 'co', name: 'Colombia', region: 'South America', roles: ['extract'] },
  { iso2: 'pa', name: 'Panama', region: 'Central America', roles: ['logistics'] },
  { iso2: 'cr', name: 'Costa Rica', region: 'Central America', roles: ['extract'] },
  { iso2: 'ni', name: 'Nicaragua', region: 'Central America', roles: ['extract'] },
  { iso2: 'hn', name: 'Honduras', region: 'Central America', roles: ['extract'] },
  { iso2: 'sv', name: 'El Salvador', region: 'Central America', roles: ['extract'] },
  { iso2: 'gt', name: 'Guatemala', region: 'Central America', roles: ['extract'] },
  { iso2: 'bz', name: 'Belize', region: 'Central America', roles: ['gap'] },
  { iso2: 've', name: 'Venezuela', region: 'South America', roles: ['extract'] },
  { iso2: 'gy', name: 'Guyana', region: 'South America', roles: ['extract'] },
  { iso2: 'sr', name: 'Suriname', region: 'South America', roles: ['extract'] },
  {
    iso2: 'fr',
    name: 'France',
    region: 'Western Europe',
    roles: ['energy', 'manufacture', 'permission', 'research'],
  },
  { iso2: 'ec', name: 'Ecuador', region: 'South America', roles: ['extract'] },
  { iso2: 'pr', name: 'Puerto Rico', region: 'Caribbean', roles: ['gap'] },
  { iso2: 'jm', name: 'Jamaica', region: 'Caribbean', roles: ['extract'] },
  { iso2: 'cu', name: 'Cuba', region: 'Caribbean', roles: ['extract'] },
  { iso2: 'zw', name: 'Zimbabwe', region: 'East Africa', roles: ['extract'] },
  { iso2: 'bw', name: 'Botswana', region: 'Southern Africa', roles: ['extract'] },
  { iso2: 'na', name: 'Namibia', region: 'Southern Africa', roles: ['gap'] },
  { iso2: 'sn', name: 'Senegal', region: 'West Africa', roles: ['extract'] },
  { iso2: 'ml', name: 'Mali', region: 'West Africa', roles: ['extract'] },
  { iso2: 'mr', name: 'Mauritania', region: 'West Africa', roles: ['extract'] },
  { iso2: 'bj', name: 'Benin', region: 'West Africa', roles: ['gap'] },
  { iso2: 'ne', name: 'Niger', region: 'West Africa', roles: ['gap'] },
  { iso2: 'ng', name: 'Nigeria', region: 'West Africa', roles: ['gap'] },
  { iso2: 'cm', name: 'Cameroon', region: 'Central Africa', roles: ['extract'] },
  { iso2: 'tg', name: 'Togo', region: 'West Africa', roles: ['gap'] },
  { iso2: 'gh', name: 'Ghana', region: 'West Africa', roles: ['extract'] },
  { iso2: 'ci', name: 'Côte d\\', region: 'West Africa', roles: ['extract'] },
  { iso2: 'gn', name: 'Guinea', region: 'West Africa', roles: ['gap'] },
  { iso2: 'gw', name: 'Guinea-Bissau', region: 'West Africa', roles: ['gap'] },
  { iso2: 'lr', name: 'Liberia', region: 'West Africa', roles: ['gap'] },
  { iso2: 'sl', name: 'Sierra Leone', region: 'West Africa', roles: ['gap'] },
  { iso2: 'bf', name: 'Burkina Faso', region: 'West Africa', roles: ['extract'] },
  { iso2: 'cf', name: 'Central African Rep.', region: 'Central Africa', roles: ['extract'] },
  { iso2: 'cg', name: 'Congo', region: 'Central Africa', roles: ['extract'] },
  { iso2: 'ga', name: 'Gabon', region: 'Central Africa', roles: ['extract'] },
  { iso2: 'gq', name: 'Eq. Guinea', region: 'Central Africa', roles: ['gap'] },
  { iso2: 'zm', name: 'Zambia', region: 'East Africa', roles: ['gap'] },
  { iso2: 'mw', name: 'Malawi', region: 'East Africa', roles: ['gap'] },
  { iso2: 'mz', name: 'Mozambique', region: 'East Africa', roles: ['extract'] },
  { iso2: 'sz', name: 'eSwatini', region: 'Southern Africa', roles: ['gap'] },
  { iso2: 'ao', name: 'Angola', region: 'Central Africa', roles: ['extract'] },
  { iso2: 'bi', name: 'Burundi', region: 'East Africa', roles: ['gap'] },
  { iso2: 'il', name: 'Israel', region: 'West Asia', roles: ['gap'] },
  { iso2: 'lb', name: 'Lebanon', region: 'West Asia', roles: ['gap'] },
  { iso2: 'mg', name: 'Madagascar', region: 'East Africa', roles: ['extract'] },
  { iso2: 'ps', name: 'Palestine', region: 'West Asia', roles: ['gap'] },
  { iso2: 'gm', name: 'Gambia', region: 'West Africa', roles: ['gap'] },
  { iso2: 'tn', name: 'Tunisia', region: 'North Africa', roles: ['extract'] },
  { iso2: 'dz', name: 'Algeria', region: 'North Africa', roles: ['extract'] },
  { iso2: 'jo', name: 'Jordan', region: 'West Asia', roles: ['extract'] },
  {
    iso2: 'ae',
    name: 'United Arab Emirates',
    region: 'West Asia',
    roles: ['capital', 'energy', 'logistics'],
  },
  { iso2: 'qa', name: 'Qatar', region: 'West Asia', roles: ['energy', 'capital', 'extract'] },
  { iso2: 'kw', name: 'Kuwait', region: 'West Asia', roles: ['extract'] },
  { iso2: 'iq', name: 'Iraq', region: 'West Asia', roles: ['extract'] },
  { iso2: 'om', name: 'Oman', region: 'West Asia', roles: ['extract'] },
  { iso2: 'vu', name: 'Vanuatu', region: 'Oceania', roles: ['gap'] },
  { iso2: 'kh', name: 'Cambodia', region: 'Southeast Asia', roles: ['extract'] },
  { iso2: 'th', name: 'Thailand', region: 'Southeast Asia', roles: ['gap'] },
  { iso2: 'la', name: 'Laos', region: 'Southeast Asia', roles: ['extract'] },
  { iso2: 'mm', name: 'Myanmar', region: 'Southeast Asia', roles: ['extract'] },
  { iso2: 'vn', name: 'Vietnam', region: 'Southeast Asia', roles: ['gap'] },
  { iso2: 'kp', name: 'North Korea', region: 'East Asia', roles: ['extract'] },
  { iso2: 'kr', name: 'South Korea', region: 'East Asia', roles: ['manufacture', 'research'] },
  { iso2: 'mn', name: 'Mongolia', region: 'East Asia', roles: ['extract'] },
  { iso2: 'in', name: 'India', region: 'South Asia', roles: ['gap'] },
  { iso2: 'bd', name: 'Bangladesh', region: 'South Asia', roles: ['extract'] },
  { iso2: 'bt', name: 'Bhutan', region: 'South Asia', roles: ['extract'] },
  { iso2: 'np', name: 'Nepal', region: 'South Asia', roles: ['extract'] },
  { iso2: 'pk', name: 'Pakistan', region: 'South Asia', roles: ['extract'] },
  { iso2: 'af', name: 'Afghanistan', region: 'South Asia', roles: ['extract'] },
  { iso2: 'tj', name: 'Tajikistan', region: 'Central Asia', roles: ['extract'] },
  { iso2: 'kg', name: 'Kyrgyzstan', region: 'Central Asia', roles: ['extract'] },
  { iso2: 'tm', name: 'Turkmenistan', region: 'Central Asia', roles: ['extract'] },
  { iso2: 'ir', name: 'Iran', region: 'South Asia', roles: ['extract'] },
  { iso2: 'sy', name: 'Syria', region: 'West Asia', roles: ['extract'] },
  { iso2: 'am', name: 'Armenia', region: 'West Asia', roles: ['extract'] },
  { iso2: 'se', name: 'Sweden', region: 'Northern Europe', roles: ['gap'] },
  { iso2: 'by', name: 'Belarus', region: 'Eastern Europe', roles: ['extract'] },
  { iso2: 'ua', name: 'Ukraine', region: 'Eastern Europe', roles: ['gap'] },
  { iso2: 'pl', name: 'Poland', region: 'Eastern Europe', roles: ['extract'] },
  { iso2: 'at', name: 'Austria', region: 'Western Europe', roles: ['extract'] },
  { iso2: 'hu', name: 'Hungary', region: 'Eastern Europe', roles: ['extract'] },
  { iso2: 'md', name: 'Moldova', region: 'Eastern Europe', roles: ['gap'] },
  { iso2: 'ro', name: 'Romania', region: 'Eastern Europe', roles: ['extract'] },
  { iso2: 'lt', name: 'Lithuania', region: 'Northern Europe', roles: ['gap'] },
  { iso2: 'lv', name: 'Latvia', region: 'Northern Europe', roles: ['gap'] },
  { iso2: 'ee', name: 'Estonia', region: 'Northern Europe', roles: ['extract'] },
  {
    iso2: 'de',
    name: 'Germany',
    region: 'Western Europe',
    roles: ['manufacture', 'research', 'energy'],
  },
  { iso2: 'bg', name: 'Bulgaria', region: 'Eastern Europe', roles: ['gap'] },
  { iso2: 'gr', name: 'Greece', region: 'Southern Europe', roles: ['extract'] },
  { iso2: 'tr', name: 'Turkey', region: 'West Asia', roles: ['gap'] },
  { iso2: 'al', name: 'Albania', region: 'Southern Europe', roles: ['gap'] },
  { iso2: 'hr', name: 'Croatia', region: 'Southern Europe', roles: ['gap'] },
  {
    iso2: 'ch',
    name: 'Switzerland',
    region: 'Western Europe',
    roles: ['capital', 'research', 'manufacture'],
  },
  { iso2: 'lu', name: 'Luxembourg', region: 'Western Europe', roles: ['capital'] },
  { iso2: 'be', name: 'Belgium', region: 'Western Europe', roles: ['logistics', 'refine'] },
  { iso2: 'nl', name: 'Netherlands', region: 'Western Europe', roles: ['manufacture', 'research'] },
  { iso2: 'pt', name: 'Portugal', region: 'Southern Europe', roles: ['extract'] },
  { iso2: 'es', name: 'Spain', region: 'Southern Europe', roles: ['extract'] },
  { iso2: 'ie', name: 'Ireland', region: 'Northern Europe', roles: ['extract'] },
  { iso2: 'nc', name: 'New Caledonia', region: 'Oceania', roles: ['extract'] },
  { iso2: 'sb', name: 'Solomon Is.', region: 'Oceania', roles: ['extract'] },
  { iso2: 'nz', name: 'New Zealand', region: 'Oceania', roles: ['gap'] },
  { iso2: 'au', name: 'Australia', region: 'Oceania', roles: ['gap'] },
  { iso2: 'lk', name: 'Sri Lanka', region: 'South Asia', roles: ['extract'] },
  {
    iso2: 'cn',
    name: 'China',
    region: 'East Asia',
    roles: ['extract', 'refine', 'manufacture', 'energy', 'permission'],
  },
  { iso2: 'tw', name: 'Taiwan', region: 'East Asia', roles: ['manufacture', 'research'] },
  { iso2: 'it', name: 'Italy', region: 'Southern Europe', roles: ['extract'] },
  { iso2: 'dk', name: 'Denmark', region: 'Northern Europe', roles: ['extract'] },
  {
    iso2: 'gb',
    name: 'United Kingdom',
    region: 'Northern Europe',
    roles: ['capital', 'research', 'permission', 'energy'],
  },
  { iso2: 'is', name: 'Iceland', region: 'Northern Europe', roles: ['extract'] },
  { iso2: 'az', name: 'Azerbaijan', region: 'West Asia', roles: ['extract'] },
  { iso2: 'ge', name: 'Georgia', region: 'West Asia', roles: ['extract'] },
  { iso2: 'ph', name: 'Philippines', region: 'Southeast Asia', roles: ['gap'] },
  { iso2: 'my', name: 'Malaysia', region: 'Southeast Asia', roles: ['gap'] },
  { iso2: 'bn', name: 'Brunei', region: 'Southeast Asia', roles: ['extract'] },
  { iso2: 'si', name: 'Slovenia', region: 'Southern Europe', roles: ['gap'] },
  { iso2: 'fi', name: 'Finland', region: 'Northern Europe', roles: ['gap'] },
  { iso2: 'sk', name: 'Slovakia', region: 'Eastern Europe', roles: ['gap'] },
  { iso2: 'cz', name: 'Czechia', region: 'Eastern Europe', roles: ['gap'] },
  { iso2: 'er', name: 'Eritrea', region: 'East Africa', roles: ['extract'] },
  { iso2: 'jp', name: 'Japan', region: 'East Asia', roles: ['manufacture', 'research'] },
  { iso2: 'py', name: 'Paraguay', region: 'South America', roles: ['gap'] },
  { iso2: 'ye', name: 'Yemen', region: 'West Asia', roles: ['extract'] },
  { iso2: 'sa', name: 'Saudi Arabia', region: 'West Asia', roles: ['energy', 'capital'] },
  { iso2: 'aq', name: 'Antarctica', region: 'Antarctica', roles: ['gap'] },
  { iso2: '', name: 'N. Cyprus', region: 'Unassigned', roles: ['gap'] },
  { iso2: 'cy', name: 'Cyprus', region: 'West Asia', roles: ['gap'] },
  { iso2: 'ma', name: 'Morocco', region: 'North Africa', roles: ['gap'] },
  { iso2: 'eg', name: 'Egypt', region: 'North Africa', roles: ['gap'] },
  { iso2: 'ly', name: 'Libya', region: 'North Africa', roles: ['extract'] },
  { iso2: 'et', name: 'Ethiopia', region: 'East Africa', roles: ['extract'] },
  { iso2: 'dj', name: 'Djibouti', region: 'East Africa', roles: ['logistics'] },
  { iso2: '', name: 'Somaliland', region: 'Unassigned', roles: ['gap'] },
  { iso2: 'ug', name: 'Uganda', region: 'East Africa', roles: ['extract'] },
  { iso2: 'rw', name: 'Rwanda', region: 'East Africa', roles: ['gap'] },
  { iso2: 'ba', name: 'Bosnia and Herz.', region: 'Southern Europe', roles: ['gap'] },
  { iso2: 'mk', name: 'Macedonia', region: 'Southern Europe', roles: ['gap'] },
  { iso2: 'rs', name: 'Serbia', region: 'Southern Europe', roles: ['gap'] },
  { iso2: 'me', name: 'Montenegro', region: 'Southern Europe', roles: ['gap'] },
  { iso2: '', name: 'Kosovo', region: 'Unassigned', roles: ['gap'] },
  { iso2: 'tt', name: 'Trinidad and Tobago', region: 'Caribbean', roles: ['extract'] },
  { iso2: 'ss', name: 'S. Sudan', region: 'East Africa', roles: ['extract'] },
];

/** Extra directory rows generated with the country index. */
export const EXTRA_ENDOWMENTS: readonly {
  iso2: string;
  resources: readonly string[];
  why: string;
}[] = [
  {
    iso2: 'af',
    resources: ['copper', 'lithium', 'rare-earths'],
    why: 'Copper, lithium, rare earths — mapped, barely industrialised.',
  },
  {
    iso2: 'am',
    resources: ['copper', 'gold'],
    why: 'Copper-molybdenum. A landlocked Caucasus minerals node.',
  },
  {
    iso2: 'ao',
    resources: ['oil', 'diamonds'],
    why: 'Atlantic oil. An energy node, not yet a manufacturing one.',
  },
  { iso2: 'aq', resources: [], why: 'Ice. Not a research geography for this map.' },
  {
    iso2: 'at',
    resources: ['hydropower'],
    why: 'Hydro, machinery, and a European industrial core.',
  },
  { iso2: 'az', resources: ['oil', 'natural-gas'], why: 'Caspian oil and gas.' },
  {
    iso2: 'bd',
    resources: ['natural-gas'],
    why: 'Gas and a dense manufacturing labour force. Not a mine.',
  },
  {
    iso2: 'be',
    resources: [],
    why: 'The port and the chemicals. Antwerp is a materials node with no mines.',
  },
  {
    iso2: 'bf',
    resources: ['gold'],
    why: 'Gold. Sahel permission is the binding constraint as much as geology.',
  },
  { iso2: 'bh', resources: ['oil'], why: 'Oil and a Gulf finance/aluminium node.' },
  { iso2: 'bn', resources: ['oil', 'natural-gas'], why: 'Oil and gas. A small energy state.' },
  { iso2: 'bs', resources: [], why: 'A services and logistics node. No mineral directory row.' },
  { iso2: 'bt', resources: ['hydropower'], why: 'Hydro exported to India. Energy as a neighbour.' },
  {
    iso2: 'bw',
    resources: ['diamonds', 'coal', 'copper'],
    why: 'Diamonds and coal. A southern African industrial state.',
  },
  { iso2: 'by', resources: [], why: 'Potash. A landlocked industrial permission case.' },
  { iso2: 'bz', resources: [], why: 'A logistics gap. No mineral directory row.' },
  {
    iso2: 'cf',
    resources: ['diamonds', 'gold'],
    why: 'Artisanal minerals. Permission and conflict, not a factory.',
  },
  { iso2: 'cg', resources: ['oil'], why: 'Oil on the Congo coast.' },
  {
    iso2: 'ci',
    resources: ['gold', 'oil'],
    why: 'The commercial capital of Francophone West Africa. Logistics more than ore.',
  },
  { iso2: 'cm', resources: ['oil', 'bauxite'], why: 'Oil and a Central African logistics hinge.' },
  {
    iso2: 'co',
    resources: ['coal', 'oil', 'nickel', 'copper'],
    why: 'Coal, oil and nickel. Andean copper on the same electrification curve as Chile and Peru.',
  },
  {
    iso2: 'cr',
    resources: ['hydropower'],
    why: 'Hydro and a high-skill manufacturing permission case.',
  },
  {
    iso2: 'cu',
    resources: ['nickel', 'cobalt'],
    why: 'Nickel-cobalt. A Caribbean battery-metals geology.',
  },
  {
    iso2: 'cz',
    resources: [],
    why: 'Machinery and a European industrial permission case. Gap: few mapped minerals.',
  },
  {
    iso2: 'dj',
    resources: [],
    why: 'The port. China, the US and France all sit on this harbour for a reason.',
  },
  {
    iso2: 'dk',
    resources: ['oil', 'natural-gas'],
    why: 'North Sea energy and a wind-industrial base.',
  },
  { iso2: 'do', resources: ['gold', 'nickel'], why: 'Gold and nickel. A Caribbean minerals node.' },
  {
    iso2: 'dz',
    resources: ['oil', 'natural-gas', 'phosphates'],
    why: 'Gas that Europe burns. Phosphates. A North African energy state.',
  },
  { iso2: 'ec', resources: ['oil', 'copper'], why: 'Oil and a Pacific copper belt.' },
  { iso2: 'ee', resources: ['oil'], why: 'Oil shale and a Baltic digital/permission case.' },
  { iso2: 'er', resources: ['copper', 'gold'], why: 'Copper-gold. A Red Sea minerals node.' },
  { iso2: 'es', resources: ['copper'], why: 'Copper and a European industrial permission case.' },
  {
    iso2: 'et',
    resources: ['hydropower', 'gold'],
    why: 'Hydropower at continental scale. The constraint is transmission and permission.',
  },
  { iso2: 'fj', resources: ['gold'], why: 'Gold and a Pacific logistics node.' },
  { iso2: 'fk', resources: [], why: 'A South Atlantic gap. No mineral directory row.' },
  { iso2: 'ga', resources: ['oil'], why: "Oil and manganese — steel's other rock." },
  {
    iso2: 'ge',
    resources: ['copper', 'gold'],
    why: 'Caucasus copper-gold and a Black Sea logistics hinge.',
  },
  {
    iso2: 'gh',
    resources: ['gold', 'oil', 'bauxite'],
    why: 'Gold, oil, bauxite. A West African industrial base next to the Sahel uranium belt.',
  },
  {
    iso2: 'gl',
    resources: ['rare-earths', 'uranium'],
    why: 'Rare earths and uranium in the Arctic. The ice is the permission system.',
  },
  {
    iso2: 'gr',
    resources: ['bauxite', 'nickel'],
    why: 'Bauxite and nickel. A Mediterranean materials node.',
  },
  { iso2: 'gt', resources: ['nickel'], why: 'Nickel. A Central American minerals node.' },
  {
    iso2: 'gy',
    resources: ['oil', 'gold', 'bauxite'],
    why: 'New offshore oil and an older bauxite/gold base.',
  },
  { iso2: 'hn', resources: ['gold', 'silver'], why: 'Gold and silver. Thin industrial base.' },
  {
    iso2: 'ht',
    resources: ['bauxite'],
    why: 'Historic bauxite. Today a permission and logistics gap.',
  },
  {
    iso2: 'hu',
    resources: ['bauxite'],
    why: 'A European battery and auto assembly node more than a mine.',
  },
  {
    iso2: 'ie',
    resources: ['natural-gas'],
    why: 'A data-centre and pharma node. Power and permission, not mines.',
  },
  { iso2: 'iq', resources: ['oil', 'natural-gas'], why: 'Oil. A Mesopotamian energy state.' },
  {
    iso2: 'ir',
    resources: ['oil', 'natural-gas', 'copper'],
    why: 'Oil, gas, copper. Sanctions make this a permission map as well as a geology one.',
  },
  {
    iso2: 'is',
    resources: ['hydropower'],
    why: 'Geothermal and hydro electrons that smelt aluminium. Energy as export.',
  },
  {
    iso2: 'it',
    resources: ['natural-gas'],
    why: 'Manufacturing, machinery, and a gas-import energy system.',
  },
  { iso2: 'jm', resources: ['bauxite'], why: "Bauxite. Aluminium's older Caribbean chapter." },
  {
    iso2: 'jo',
    resources: ['phosphates'],
    why: 'Phosphates. A logistics hinge next to the Red Sea.',
  },
  {
    iso2: 'ke',
    resources: ['hydropower'],
    why: 'East African industrial and geothermal power node. Materials mostly next door.',
  },
  { iso2: 'kg', resources: ['gold'], why: 'Gold. A Central Asian minerals node.' },
  {
    iso2: 'kh',
    resources: ['bauxite'],
    why: 'A manufacturing absorber. Minerals thin; assembly is the story.',
  },
  {
    iso2: 'kp',
    resources: ['coal', 'iron', 'rare-earths'],
    why: 'Coal, iron, rare earths — almost none of it in open trade.',
  },
  { iso2: 'kw', resources: ['oil', 'natural-gas'], why: 'Oil. A Gulf capital and energy state.' },
  {
    iso2: 'la',
    resources: ['hydropower', 'copper'],
    why: 'Hydro and copper. A landlocked Mekong industrial case.',
  },
  {
    iso2: 'lb',
    resources: [],
    why: 'A Mediterranean services node. Gap: no mineral directory row.',
  },
  { iso2: 'lk', resources: ['graphite'], why: 'Natural graphite. Anodes.' },
  { iso2: 'lt', resources: [], why: 'Baltic logistics and a small industrial base.' },
  { iso2: 'lu', resources: [], why: 'Capital and steel history. Finance more than ore.' },
  { iso2: 'lv', resources: [], why: 'Baltic logistics. Gap: no mineral directory row.' },
  {
    iso2: 'ly',
    resources: ['oil', 'natural-gas'],
    why: 'Oil and gas. North African energy that Europe still feels.',
  },
  { iso2: 'md', resources: [], why: 'A landlocked European gap. No mineral directory row.' },
  {
    iso2: 'mg',
    resources: ['nickel', 'graphite', 'rare-earths'],
    why: 'Nickel, graphite, and a rare-earth project pipeline.',
  },
  {
    iso2: 'ml',
    resources: ['gold', 'lithium'],
    why: 'Gold and lithium pegmatites. The resource is not yet a chemical plant.',
  },
  {
    iso2: 'mm',
    resources: ['rare-earths', 'tin', 'natural-gas'],
    why: 'Rare earths, tin, gas. A Southeast Asian materials hinge.',
  },
  {
    iso2: 'mn',
    resources: ['copper', 'coal', 'gold'],
    why: 'Copper that feeds Chinese refining. A mine next to the midstream.',
  },
  {
    iso2: 'mr',
    resources: ['iron', 'gold'],
    why: "Iron ore to the Atlantic. One of West Africa's actual bulk-export geologies.",
  },
  {
    iso2: 'mz',
    resources: ['natural-gas', 'coal', 'graphite'],
    why: 'LNG and graphite. Energy and anodes.',
  },
  {
    iso2: 'nc',
    resources: ['nickel'],
    why: 'Nickel laterites. The same battery curve as Indonesia and the Philippines.',
  },
  { iso2: 'ni', resources: ['gold'], why: 'Gold. A Central American minerals gap.' },
  { iso2: 'np', resources: ['hydropower'], why: 'Himalayan hydro. Transmission is the wait.' },
  {
    iso2: 'om',
    resources: ['oil', 'natural-gas', 'copper'],
    why: 'Oil, gas, copper. A Gulf industrial permission case.',
  },
  {
    iso2: 'pa',
    resources: [],
    why: "The canal. Logistics for everyone else's copper and containers.",
  },
  {
    iso2: 'pg',
    resources: ['copper', 'gold', 'natural-gas'],
    why: 'Copper-gold and LNG. A Pacific materials node.',
  },
  {
    iso2: 'pk',
    resources: ['coal', 'natural-gas'],
    why: 'Coal, gas, and a large industrial population. Permission and power.',
  },
  {
    iso2: 'pl',
    resources: ['coal', 'copper'],
    why: 'Copper and coal. A European industrial permission problem.',
  },
  {
    iso2: 'pr',
    resources: [],
    why: 'A US manufacturing and power-system case. No mineral directory row.',
  },
  { iso2: 'ps', resources: [], why: 'No mineral directory row. Permission is the entire story.' },
  {
    iso2: 'pt',
    resources: ['lithium', 'copper'],
    why: 'European lithium and an older tungsten story.',
  },
  {
    iso2: 'qa',
    resources: ['natural-gas'],
    why: "LNG. Firm gas that other people's industry burns.",
  },
  { iso2: 'ro', resources: ['natural-gas', 'coal'], why: 'Gas and a Black Sea industrial base.' },
  {
    iso2: 'rw',
    resources: [],
    why: 'A dense state trying to be a services and assembly node. Gap: almost no mapped materials.',
  },
  { iso2: 'sb', resources: ['gold'], why: 'Gold. A Pacific gap with a thin industrial base.' },
  {
    iso2: 'sd',
    resources: ['gold', 'oil'],
    why: 'Gold and oil. A Red Sea logistics and permission problem.',
  },
  { iso2: 'sk', resources: [], why: 'Auto and machinery. Same story as Czechia.' },
  { iso2: 'sn', resources: ['phosphates', 'oil'], why: 'Phosphates and new offshore oil/gas.' },
  {
    iso2: 'so',
    resources: [],
    why: 'Indian Ocean coastline. No mineral directory row; logistics and permission are the open questions.',
  },
  {
    iso2: 'sr',
    resources: ['oil', 'gold', 'bauxite'],
    why: 'Same Guiana shield as Guyana: oil arriving on an older minerals base.',
  },
  { iso2: 'ss', resources: ['oil'], why: 'Oil. The state is the constraint.' },
  { iso2: 'sv', resources: ['gold'], why: 'A dense manufacturing labour force. Not a mine.' },
  {
    iso2: 'sy',
    resources: ['oil', 'phosphates'],
    why: 'Oil and phosphates. The state is the constraint.',
  },
  {
    iso2: 'td',
    resources: ['oil'],
    why: 'Landlocked oil. Energy that does not yet industrialise at home.',
  },
  { iso2: 'tf', resources: [], why: 'Southern ocean. Not a research geography.' },
  {
    iso2: 'tj',
    resources: ['hydropower', 'gold'],
    why: 'Hydro in the Pamirs. Energy as mountains.',
  },
  {
    iso2: 'tl',
    resources: ['oil', 'natural-gas'],
    why: 'Timor Sea energy. A young state on a hydrocarbon basin.',
  },
  {
    iso2: 'tm',
    resources: ['natural-gas'],
    why: "Among the world's large gas endowments. A pipeline state.",
  },
  {
    iso2: 'tn',
    resources: ['phosphates', 'oil'],
    why: 'Phosphates and a Mediterranean industrial permission case.',
  },
  { iso2: 'tt', resources: ['natural-gas', 'oil'], why: 'Gas and a Caribbean chemicals/LNG node.' },
  {
    iso2: 'tz',
    resources: ['gold', 'hydropower'],
    why: 'Gold and a growing power system on the Indian Ocean logistics lane.',
  },
  {
    iso2: 'ug',
    resources: ['oil', 'gold'],
    why: 'Albertine oil and a landlocked industrial permission problem.',
  },
  {
    iso2: 'uy',
    resources: ['hydropower'],
    why: 'A small, high-skill grid. Interesting as a permission and power-system case, not as ore.',
  },
  {
    iso2: 've',
    resources: ['oil', 'natural-gas'],
    why: 'One of the largest oil endowments on earth. Energy as a state, not just a well.',
  },
  { iso2: 'vu', resources: [], why: 'Pacific gap. No mineral directory row.' },
  {
    iso2: 'ye',
    resources: ['oil'],
    why: "Oil and a Bab el-Mandeb logistics chokepoint for everyone else's energy.",
  },
  {
    iso2: 'zw',
    resources: ['lithium', 'gold', 'pgms'],
    why: 'Hard-rock lithium and gold. The resource is not the chemical.',
  },
];
